# Generated by Django 4.2 on 2023-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('review_body', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('best_or_worst', models.TextField()),
            ],
        ),
    ]
