# Generated by Django 4.2 on 2023-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='best_or_worst',
        ),
        migrations.AddField(
            model_name='reviews',
            name='polarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='sentiment',
            field=models.TextField(blank=True, default='neutral'),
        ),
    ]
